##############################################
# +----------------------------------------+ #
# |             Combat Tagging             | #
# +----------------------------------------+ #
##############################################

# Settings related to the combat tagger mechanics.

combat_tagger:
  # Enable or disable the feature.
  enabled: true
  # Duration of a combat tag, in seconds.
  # Cannot be lower than 1.
  duration: 30
  # List of blocked commands to not allow during combat.
  # NOTE: Any command containing the word 'warp' anywhere is hard-coded to be blocked.
  blocked-commands:
    - 'tp'
    - 'tpa'
    - 'tpahere'
    - 'tpaccept'
    - 'tpadeny'
    - 'fly'
    - 'spawn'
    - 'rtp'
    - 'warp'
    - 'home'
    - 'sethome'
    - 'suicide'
    - 'trade'
    - 'ender'
    - 'enderchest'
    - 'ec'
    - 'warp'
  # Backup setting to block command and plugin initiated teleports if command blacklisting isn't enough.
  disable-warping: true
  # Disable sitting on other players during combat.
  # Only works with the GSit plugin by Gecolay.
  disable-sitting: true
  # Worlds in this list are not affected by combat tagging.
  blocked-worlds:
    - 'world_arena1'
    - 'world_arena2'
  # Worlds where combat tagging is enabled but not combat logging punishments.
  unpunishable-worlds:
    - 'world_arena3'
    - 'world_arena4'
  # Players with this permission are not affected by combat tagging.
  bypass-permission: united.combat.bypass

  # Settings for the bossbar that appears to players who are in combat.
  bossbar:
    # Enable to disable the boss bar function.
    enabled: true
    # Text displayed within the bossbar.
    title: "<red>In Combat (<yellow><bold>%seconds%s<red>)"
    # Bossbar colour, only supports:
    # PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
    colour: "RED"
    # Boss bar styling, only supports:
    # SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
    style: "SOLID"
    # How long to linger the bar after it's finished (for a smooth transition)
    # Measured in milliseconds, default is 1000
    linger: 1000

  # Flight control settings.
  flight:
    # Enable or disable plugin or command flight during combat.
    plugin-flight: true
    # Enable or disable elytra flight during combat.
    # This also cancels the use of trident riptides.
    elytra-flight: true
    # Cancel first fall damage after disabling flight.
    # Requires flight controls to be TRUE.
    soft-landing: true

  # What command(s) to run if a player logs out in combat.
  combat-log-punishments:
    # Enable or disable escalating punishments.
    # When TRUE, combat logging is recorded and each successive time can run different commands for harsher punishments.
    # When FALSE, only the first configured list of punishments are ever applied.
    punishment-escalation: true
    1:
      - 'warn %player_name% Combat logging, 1st offence.'
    2:
      - 'warn %player_name% Combat logging, 2nd offence.'
      - 'kill %player_name%'
    3:
      - 'tempban %player_name% 3d Combat logging, 3rd offence.'
      - 'kill %player_name%'
    4:
      - 'ban %player_name% Combat logging, 4th offence.'
      - 'kill %player_name'

##############################################
# +----------------------------------------+ #
# |               Explosions               | #
# +----------------------------------------+ #
##############################################

# This section covers all the explosion tweaks for PvP.

end-crystals:
  # Toggle on or off vanilla crystal behaviour.
  nerf-crystal-damage: true
  # The damage the crystal will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  crystal-damage-percent: 0

respawn-anchors:
  # Toggle on or off vanilla anchor behaviour.
  nerf-anchor-damage: true

minecarts:
  # Toggle on or off vanilla minecart behaviour.
  nerf-minecart-damage: true
  # The damage the minecart will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  minecart-damage-percent: 0

mace:
  # Toggle on or off damage cap for maces.
  nerf-mace-damage: true
  # The max amount of mace damage applied to players in pvp
  mace_max_damage: 75

##############################################
# +----------------------------------------+ #
# |                Hostility               | #
# +----------------------------------------+ #
##############################################

hostility-icons:
  defensive: 'ðŸ›¡'
  aggressive: 'âš”'
  hostile: 'â˜ '

hostility-thresholds:
  defensive: 1
  aggressive: 7
  hostile: 15

hostility-exempt-worlds:
  - 'world_arena1'
  - 'world_arena2'

hostility-colour-stages:
  0: '#E6850B'
  1: '#E6850B'
  2: '#E6850B'
  3: '#E6850B'
  4: '#E6850B'
  5: '#E6850B'
  6: '#EE7878'
  7: '#EE7878'
  8: '#EF6A6A'
  9: '#EF5959'
  10: '#EF4949'
  11: '#E73B3B'
  12: '#E73B3B'
  13: '#E73B3B'
  14: '#CF2929'
  15: '#CF2929'
  16: '#B12323'
  17: '#982020'
  18: '#861D1D'
  19: '#6E1717'
  20: '#541111'
  21: '#360B0B'

##############################################
# +----------------------------------------+ #
# |          Attribute swapping            | #
# +----------------------------------------+ #
##############################################

# List of items that should trigger updating attributes immediately upon 
# quickbar change to fix e.g. breach swapping 
attr-swap-items:
- WOODEN_SWORD
- STONE_SWORD
- IRON_SWORD
- GOLDEN_SWORD
- DIAMOND_SWORD
- NETHERITE_SWORD
- WOODEN_AXE
- STONE_AXE
- IRON_AXE
- GOLDEN_AXE
- DIAMOND_AXE
- NETHERITE_AXE
- MACE

##############################################
# +----------------------------------------+ #
# |                Language                | #
# +----------------------------------------+ #
##############################################

# This section has editable language configurations for plugin messages.

messages:
  prefix: "<bold><red>U</red><white>L</white> Combat <dark_gray>Â» </dark_gray></bold>"
  reload: "<dark_green>Plugin reloaded."
  invalid-command: "<red>Invalid command usage."
  no-permission: '<dark_green>You don''t have permission to perform this command.'
  help-message:
    - '<bold><red>United <white>Combat</bold>'
    - '<dark_gray>/pvp degrade [on/off] <gray>Toggle hostility decrease every new Towny day.'
    - '<dark_gray>/pvp status [player] <gray>Show your current status and hostility points. Add a player name to display their status.'
    - '<dark_gray>/pvp mute <gray>Mute or unmute neutrality warning notifications.'
    - '<dark_gray>/pvp on <gray>Disable your new player immunity.'
  in-combat: '<red>You can''t use that command while in combat!'
  pvp-disabled: '<red>PvP disabled!'
  pvp-enabled: '<green>PvP enabled.'
  pvp-degrade-enabled: '<green>Enabled hostility degradation.'
  pvp-degrade-disabled: '<red>Disabled hostility degradation.'
  player-not-recognised: '<red>Player not found.'
  pvp-status: '<gray>{name}''s status is <yellow><bold>{status}</bold><gray>, with <yellow><bold>{hostility}</bold> <gray>hostility points.'
  you-are-immune: '<red>You are immune for <yellow><bold>{time}</bold></yellow>. <gray>Please do <dark_gray>/pvp on <red>to attack this player!'
  target-immune: '<red>Player is new is immune to attacks!'
  immunity-removed: '<red>You are no longer immune to attacks, and can attack other players!'
  you-are-not-immune: '<red>You are not immune to attacks!'
  kicked-out-of-neutrality-mayor: '<red>Your town is no longer neutral! You cannot change this as long as you have hostile residents in your town.'
  kicked-out-of-neutrality-king: '<red>Your nation is no longer neutral! You cannot change this as long as you have hostile towns in your nation!'
  cannot-be-neutral: '<red>You cannot toggle your town neutrality! You have hostile players in your town, found players: <yellow><bold>{players}</bold><red>. You can mute this message using <dark_gray>/pvp mute<gray>.'
  cannot-be-neutral-nation: '<red>You cannot toggle your nation neutrality! You have hostile towns in your nation, found towns: <yellow><bold>{towns}</bold><red>. You can mute this message using <dark_gray>/pvp mute<gray>.'
  muted-notif: '<red>Neutrality warning notifications have been muted! Run <dark_gray>/pvp mute <red>again to unmute.'
  unmuted-notif: '<green>Neutrality warning notifications unmuted! Run <dark_gray>/pvp mute <green>to mute them again.'
  kicked-out-of-neutrality: '<red>Your town has lost neutrality due to your actions!'
  unknown-player: '<red>The player could not be found.'
  admin-pvp-degrade-enabled: '<green>Enabled <gray>hostility degradation for player.'
  admin-pvp-degrade-disabled: '<red>Disabled <gray>hostility degradation for player.'
  admin-immunity-removed: '<gray>The player''s immunity has been removed.'
  admin-hostility-updated: '<gray>Hostility level for player updated.'
  admin-player-not-immune: '<yellow>This player did not have immunity.'
  admin-help-message:
    - '<bold><red>United <white>Combat <gray>Admin Commmands'
    - '<dark_gray>/ca [player] degrade [on/off] <gray>Toggles the player''s hostility decrease every new Towny day.'
    - '<dark_gray>/ca [player] sethostility [1-21] <gray>Sets the player''s hostility level.'
    - '<dark_gray>/ca [player] forcepvp <gray>Force-disables pvp immunity for new players.'

# +---------------------------------------------+ #
# |              Combat Tagging                 | #
# +---------------------------------------------+ #

  combat-tagged: '<red>You are now in combat! Do not log out.'
  combat-tagged-expired: '<green>You are no longer in combat.'
  combat-tagged-blocked-command: '<red>You cannot use that command in combat.'
  # {0} is the opponent's username.
  combat-tagged-opponent-logout: '<yellow><bold>{0} <green>logged out, you are no longer in combat.'