##############################################
# +----------------------------------------+ #
# |             Combat Tagging             | #
# +----------------------------------------+ #
##############################################

# Settings related to the combat tagger mechanics.

combat_tagger:
  # Enable or disable the feature.
  enabled: true
  # Duration of a combat tag, in seconds.
  # Cannot be lower than 1.
  duration: 30
  # List of blocked commands to not allow during combat.
  blocked-commands:
    - 'tp'
    - 'tpa'
    - 'tpahere'
    - 'tpaccept'
    - 'tpadeny'
    - 'fly'
    - 'spawn'
    - 'rtp'
    - 'warp'
    - 'home'
    - 'sethome'
    - 'suicide'
    - 'trade'
    - 'ender'
    - 'enderchest'
    - 'ec'
    - 'warp'
  # Worlds in this list are not affected by combat tagging.
  blocked-worlds:
    - 'world_arena1'
    - 'world_arena2'
  # Players with this permission are not affected by combat tagging.
  bypass-permission: united.combat.bypass
  # What command(s) to run if a player logs out in combat.
  combat-log-commands:
    - 'warn %player_name% You have been warned for logging out in combat.'
    - 'kill %player_name%'
  # Settings for the bossbar that appears to players who are in combat.
  bossbar:
    # Enable to disable the boss bar function.
    enabled: true
    # Text displayed within the bossbar.
    title: "§cIn Combat (§e§l%seconds%s§c)"
    # Bossbar colour, only supports:
    # PINK, BLUE, RED, GREEN, YELLOW, PURPLE, WHITE
    colour: "RED"
    # Boss bar styling, only supports:
    # SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
    style: "SOLID"
    # How long to linger the bar after it's finished (for a smooth transition)
    # Measured in milliseconds, default is 1000
    linger: 1000

##############################################
# +----------------------------------------+ #
# |               Explosions               | #
# +----------------------------------------+ #
##############################################

# This section covers all the explosion tweaks for PvP.

end-crystals:
  # Toggle on or off vanilla crystal behaviour.
  nerf-crystal-damage: true
  # The damage the crystal will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  crystal-damage-percent: 0

respawn-anchors:
  # Toggle on or off vanilla anchor behaviour.
  nerf-anchor-damage: true

minecarts:
  # Toggle on or off vanilla minecart behaviour.
  nerf-minecart-damage: true
  # The damage the minecart will do, in %. 0 will do no damage, 50 will do half damage, and 100 will do full damage.
  minecart-damage-percent: 0

##############################################
# +----------------------------------------+ #
# |                Hostility               | #
# +----------------------------------------+ #
##############################################

hostility-exempt-worlds:
  - 'world_arena1'
  - 'world_arena2'

hostility-colour-stages:
  0: '#E6850B'
  1: '#E6850B'
  2: '#E6850B'
  3: '#E6850B'
  4: '#E6850B'
  5: '#E6850B'
  6: '#EE7878'
  7: '#EE7878'
  8: '#EF6A6A'
  9: '#EF5959'
  10: '#EF4949'
  11: '#E73B3B'
  12: '#E73B3B'
  13: '#E73B3B'
  14: '#CF2929'
  15: '#CF2929'
  16: '#B12323'
  17: '#982020'
  18: '#861D1D'
  19: '#6E1717'
  20: '#541111'
  21: '#360B0B'

##############################################
# +----------------------------------------+ #
# |          Attribute swapping            | #
# +----------------------------------------+ #
##############################################

# List of items that should trigger updating attributes immediately upon 
# quickbar change to fix e.g. breach swapping 
attr-swap-items:
- WOODEN_SWORD
- STONE_SWORD
- IRON_SWORD
- GOLDEN_SWORD
- DIAMOND_SWORD
- NETHERITE_SWORD
- WOODEN_AXE
- STONE_AXE
- IRON_AXE
- GOLDEN_AXE
- DIAMOND_AXE
- NETHERITE_AXE
- MACE

##############################################
# +----------------------------------------+ #
# |                Language                | #
# +----------------------------------------+ #
##############################################

# This section has editable language configurations for plugin messages.

messages:
  prefix: "§c§lU§f§lL §7§lCombat §8§l» "
  reload: "§2Plugin reloaded."
  invalid-command: "§cInvalid command usage."
  no-permission: '§2You don''t have permission to perform this command.'
  help-message:
    - '§l§cUnited §fCombat'
    - '§8/pvp degrade [on/off] §7Toggle hostility decrease every new Towny day.'
    - '§8/pvp status [player] §7Show your current status and hostility points. Add a player name to display their status.'
    - '§8/pvp mute §7Mute or unmute neutrality warning notifications.'
    - '§8/pvp on §7Disable your new player immunity.'
  in-combat: '§cYou can''t use that command while in combat!'
  pvp-disabled: '§cPvP disabled!'
  pvp-enabled: '§aPvP enabled.'
  pvp-degrade-enabled: '§aEnabled hostility degradation.'
  pvp-degrade-disabled: '§cDisabled hostility degradation.'
  player-not-recognised: '§cPlayer not found.'
  pvp-status: '§7<name>'' status is §e§l<status>§7, with §e§l<hostility> §7hostility points.'
  you-are-immune: '§cYou are immune for §e§l<time>. §7Please do §8/pvp on §cto attack this player!'
  target-immune: '§cPlayer is new is immune to attacks!'
  immunity-removed: '§cYou are no longer immune to attacks, and can attack other players!'
  you-are-not-immune: '§cYou are not immune to attacks!'
  kicked-out-of-neutrality-mayor: '§cYour town is no longer neutral! You cannot change this as long as you have hostile residents in your town.'
  kicked-out-of-neutrality-king: '§cYour nation is no longer neutral! You cannot change this as long as you have hostile towns in your nation!'
  cannot-be-neutral: '§cYou cannot toggle your town neutrality! You have hostile players in your town, found players: §e§l<players>§c. You can mute this message using §8/pvp mute§7.'
  cannot-be-neutral-nation: '§cYou cannot toggle your nation neutrality! You have hostile towns in your nation, found towns: §e§l<towns>§c. You can mute this message using §8/pvp mute§7.'
  muted-notif: '§cNeutrality warning notifications have been muted! Run §8/pvp mute §cagain to unmute.'
  unmuted-notif: '§aNeutrality warning notifications unmuted! Run §8/pvp mute §ato mute them again.'
  kicked-out-of-neutrality: '§cYour town has lost neutrality due to your actions!'
  unknown-player: '§cThe player could not be found.'
  admin-pvp-degrade-enabled: '§aEnabled §7hostility degradation for player.'
  admin-pvp-degrade-disabled: '§cDisabled §7hostility degradation for player.'
  admin-immunity-removed: '§7The player''s immunity has been removed.'
  admin-hostility-updated: '§7Hostility level for player updated.'
  admin-player-not-immune: '§eThis player did not have immunity.'
  admin-help-message:
    - '§l§cUnited §fCombat §7Admin Commmands'
    - '§8/ca [player] degrade [on/off] §7Toggles the player''s hostility decrease every new Towny day.'
    - '§8/ca [player] sethostility [1-21] §7Sets the player''s hostility level.'
    - '§8/ca [player] forcepvp §7Force-disables pvp immunity for new players.'

# +---------------------------------------------+ #
# |              Combat Tagging                 | #
# +---------------------------------------------+ #

combat-tagged: '§cYou are now in combat! Do not log out.'
combat-tagged-blocked-command: '§cYou cannot use that command in combat.'